# Generated by Django 4.0 on 2021-12-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_name', models.CharField(max_length=200)),
                ('pkg_code', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('global_enable', models.BooleanField(default=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
